# Generated by Django 4.2 on 2023-04-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_staff_gymuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='club',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
