# Generated by Django 4.2 on 2023-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_gymuser_club_alter_gymuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mediaStorage/users'),
        ),
    ]
