# Generated by Django 4.2 on 2023-04-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_gymuser_club_alter_gymuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='club',
            field=models.CharField(choices=[('club1', 'Київ, вул. Уявна 12'), ('club2', 'Київ, вул. Нова 26'), ('club3', 'Київ, вул. Довга 102'), ('club4', 'Київ, вул. Чудова 19'), ('club5', 'Київ, вул. Зелена 66'), ('club6', 'Київ, вул. Технологічна 8')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='mediaStoragemediaStorage/users'),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='plan',
            field=models.CharField(choices=[('STARTER', 'STARTER'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM'), ('PREMIUM SPA', 'PREMIUM SPA')], max_length=20, null=True),
        ),
    ]
