# Generated by Django 4.2 on 2023-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_gymuser_club_alter_gymuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
