# Generated by Django 4.2 on 2023-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_gymuser_is_staff_alter_gymuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mediaStorage/users'),
        ),
    ]
