# Generated by Django 4.2 on 2023-04-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_gymuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='photo',
        ),
    ]
