# Generated by Django 4.2 on 2023-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_gymuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='club',
        ),
        migrations.RemoveField(
            model_name='gymuser',
            name='plan',
        ),
        migrations.AddField(
            model_name='gymuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mediaStorage/users'),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
