# Generated by Django 4.2 on 2023-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_gymuser_club_remove_gymuser_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
