# Generated by Django 4.2 on 2023-04-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_gymuser_is_staff_alter_gymuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='photo',
        ),
    ]
