# Generated by Django 4.2 on 2023-04-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_gymuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mediaStorage/users'),
        ),
    ]
