# Generated by Django 4.2 on 2023-05-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_gymtrainer_photo'),
        ('accounts', '0022_alter_gymuser_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gymtrainer'),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
