# Generated by Django 4.2 on 2023-04-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_type_products_p_type_alter_products_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tastes',
        ),
    ]
