# Generated by Django 4.2 on 2023-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_products_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tastes',
            field=models.JSONField(default='Без смаку', verbose_name='tastes'),
        ),
    ]
