# Generated by Django 4.2 on 2023-04-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_gymuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymUser',
        ),
    ]
