# Generated by Django 4.2 on 2023-05-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cart_taste'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='mediaStorage/trainers')),
            ],
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.DeleteModel(
            name='Translations',
        ),
    ]
