# Generated by Django 4.2 on 2023-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_gymtrainer_delete_clubs_delete_plans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymtrainer',
            name='photo',
            field=models.ImageField(upload_to='trainers'),
        ),
    ]
