# Generated by Django 4.2 on 2023-05-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_gymtrainer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymtrainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers'),
        ),
    ]
