# Generated by Django 4.2 on 2023-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_gymtrainer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymtrainer',
            name='photo',
            field=models.ImageField(default=None, upload_to='trainers'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tastes',
            field=models.JSONField(default='{"unflavored": "Без смаку", "vanilla ice cream": "Ванільне морозиво", "banana": "Банан", "strawberry milkshake": "Полуничний мілкшейк", "chocolate": "Шоколад", "coconut": "Кокос"}', verbose_name='tastes'),
        ),
    ]
