# Generated by Django 4.2 on 2023-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_gymtrainer_photo_alter_products_tastes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tastes',
            field=models.JSONField(default='Без смаку', verbose_name='tastes'),
        ),
    ]
